---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iis-deployment
spec:
  selector:
    matchLabels:
      app: iis
  replicas: 1
  template:
    metadata:
      labels:
        app: iis
    spec:
      containers:
      - name: iis-site
        image: iis-site
        ports:
        - containerPort: 80
          protocol: TCP