apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-nginx
spec:
  replicas: 3
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: my-nginx
    spec:
      containers:
        - image: nginx
          imagePullPolicy: Always
          name: my-nginx
          ports:
            - containerPort: 80