---
apiVersion: v1
kind: Service
metadata:
   name: sur_test_svc
   namespace: staging
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 31111
  selector:
    app: surtest